### ISSUE TITLE
"Sort by" in Collection view has no effect 

### ISSUE THREAD

**Issue by ocaisa** [ncsa/clowder#5] opened 2018-01-19 11:10 UTC
It seems that the `Sort By` button in the `Collection` view has no effect, the order is always `dateN`. The information in the cookie is updated correctly though so I'm not sure where the problem occurs. Also, assuming this did work, is there is way to set a default ordering for our instance?

Below I show how changing `Newest` to `Oldest` has no effect but I've also tried all other options.

<img width="580" alt="order-newest" src="https://user-images.githubusercontent.com/3840437/35148176-986ff334-fd11-11e7-8a6d-d21fd9ae20fb.png">

<img width="580" alt="order-oldest" src="https://user-images.githubusercontent.com/3840437/35148177-989030fe-fd11-11e7-95c5-10eaf006decd.png">

**Comment by indiragp** [comment] 2018-01-23 16:51
Hi @ocaisa the sorting should be enabled in custom.conf with 
sortInMemory = true 
It is a bug that the sorting dropdown is currently showing up with the flag being off. I am working on that issue. And will be fixed on the next release, the reference for the issue is: https://opensource.ncsa.illinois.edu/jira/browse/CATS-840 
If you update the flag in custom.conf the functionality for sorting will work correctly.

**Comment by indiragp** [comment] 2018-01-23 18:17
The update to check for the sortInMemory flag in the collections page is now in develop.

**Closed** 2018-01-23 18:22 UTC
